
@startuml

title SmartHome Container Diagram
top to bottom direction



!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

Person(smarthome_user, "Пользователь")

System(smarthome_app, "Тёплый дом", "Монолитное приложение удалённого управления отоплением в доме.")
Container_Boundary(smarthome_app, "Система умного дома") {
  Container(smarthome_web, "Веб приложение")
  Container(smarthome_device, "Управление устройствами")
  Container(smarthome_script, "Управление сценариями")
  Container(smarthome_notification, "Управление уведомлениями")
  Container(smarthome_user_profile, "Управление пользователями")
  Container(smarthome_database, "Database", "PostgreSQL")
}
System_Ext(temperature_service, "API сервиса температуры", "API сервиса температуры, получает температуру с датчиков.")
System_Ext(payment_system, "Система платежей", "Система платежей, получает платежи от пользователей.")
System_Ext(notification_system, "Сервис уведомлений", "Сервис уведомлений, отправляет уведомления пользователям по sms, email, push.")


Rel(smarthome_user, smarthome_web, "Управляет подпиской, устройствами и сценариями")
Rel(smarthome_web, smarthome_user_profile, "Управление, аутентификация, авторизация пользователей и их профилями.")
Rel(smarthome_web, smarthome_device, "Управление, взаимодействие с устройствами.")
Rel(smarthome_web, smarthome_script, "Управление, взаимодействие с сценариями.")
Rel(smarthome_web, smarthome_notification, "Управление, взаимодействие с уведомлениями.")

Rel(smarthome_user_profile, smarthome_database, "Чтение, запись пользователей и их профилями.")
Rel(smarthome_device, smarthome_database, "Чтение, запись устройств.")
Rel(smarthome_script, smarthome_database, "Чтение, запись сценариев.")
Rel(smarthome_notification, smarthome_database, "Чтение, запись уведомлений.")

Rel(smarthome_device, temperature_service, "Получение температуры", "REST")
Rel(smarthome_user_profile, payment_system, "Оплата подписки", "REST")

Rel(payment_system, notification_system, "Отправка уведомлений о платежах", "REST")
Rel(smarthome_notification, notification_system, "Отправка уведомлений об устройствах", "REST")
Rel(notification_system, smarthome_user, "Получение уведомлений", "REST")

@enduml