@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "Пользователь", "Клиент компании 'Тёплый дом'")
Person(installer, "Специалист", "Специалист выполняющий работы для компании 'Тёплый дом'")

System(system, "Тёплый дом", "Монолитное приложение удалённого управления отоплением в доме.")
System(sensor, "Сервис температуры", "Сервис температуры, который получает температуру с датчиков температуры и сохраняет в базу данных.")

Rel(user, system, "Управляет отоплением, проверяет температуру через веб-интерфейс")
Rel(installer, system, "Настройка систем отопления (добавление, обновление, удаление датчиков температуры).")
Rel(system, sensor, "Запрашивает температуру", "REST")

@enduml